// <auto-generated />
using System;
using Ecomads.WebApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ecomads.WebApplication.Migrations
{
    [DbContext(typeof(EcomadsDbContext))]
    [Migration("20260401151212_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.Compaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("number");

                    b.HasKey("Id");

                    b.ToTable("compaigns", (string)null);
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.CompaignStatistics", b =>
                {
                    b.Property<Guid>("CompaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("compaign_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<float>("Clicks")
                        .HasColumnType("real")
                        .HasColumnName("clicks");

                    b.Property<float>("Ctr")
                        .HasColumnType("real")
                        .HasColumnName("ctr");

                    b.Property<float>("Drr")
                        .HasColumnType("real")
                        .HasColumnName("drr");

                    b.Property<float>("Revenue")
                        .HasColumnType("real")
                        .HasColumnName("revenue");

                    b.Property<float>("Spend")
                        .HasColumnType("real")
                        .HasColumnName("spend");

                    b.HasKey("CompaignId", "StartDate", "EndDate", "Type");

                    b.ToTable("compaign_statistics", (string)null);
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.Seller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("sellers", (string)null);
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.CompaignStatistics", b =>
                {
                    b.HasOne("Ecomads.WebApplication.Data.Models.Compaign", null)
                        .WithMany()
                        .HasForeignKey("CompaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
