// <auto-generated />
using System;
using Ecomads.WebApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ecomads.WebApplication.Migrations
{
    [DbContext(typeof(EcomadsDbContext))]
    [Migration("20261001142456_AddMinCtrNorm")]
    partial class AddMinCtrNorm
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<string>("WbCampaignId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("wb_campaign_id");

                    b.Property<int?>("WbStatus")
                        .HasColumnType("integer")
                        .HasColumnName("wb_status");

                    b.HasKey("Id");

                    b.HasIndex("StoreId", "WbCampaignId")
                        .IsUnique();

                    b.ToTable("campaigns", (string)null);
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.CampaignNomenclatureStatistics", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<Guid>("NomenclatureId")
                        .HasColumnType("uuid")
                        .HasColumnName("nomenclature_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<decimal?>("AveragePosition")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("average_position");

                    b.Property<int>("Cancellations")
                        .HasColumnType("integer")
                        .HasColumnName("cancellations");

                    b.Property<int>("Carts")
                        .HasColumnType("integer")
                        .HasColumnName("carts");

                    b.Property<int>("Clicks")
                        .HasColumnType("integer")
                        .HasColumnName("clicks");

                    b.Property<decimal?>("Cpc")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("cpc");

                    b.Property<decimal?>("Cpm")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("cpm");

                    b.Property<decimal?>("Cpo")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("cpo");

                    b.Property<decimal?>("Cr")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("cr");

                    b.Property<decimal?>("Ctr")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("ctr");

                    b.Property<int>("Impressions")
                        .HasColumnType("integer")
                        .HasColumnName("impressions");

                    b.Property<int>("Orders")
                        .HasColumnType("integer")
                        .HasColumnName("orders");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("revenue");

                    b.Property<decimal>("Spend")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("spend");

                    b.HasKey("CampaignId", "NomenclatureId", "Date");

                    b.HasIndex("NomenclatureId", "Date");

                    b.ToTable("campaign_nomenclature_statistics", (string)null);
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.CampaignStatistics", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("Cancellations")
                        .HasColumnType("integer")
                        .HasColumnName("cancellations");

                    b.Property<int>("Carts")
                        .HasColumnType("integer")
                        .HasColumnName("carts");

                    b.Property<int>("Clicks")
                        .HasColumnType("integer")
                        .HasColumnName("clicks");

                    b.Property<decimal>("Ctr")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("ctr");

                    b.Property<decimal>("Drr")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("drr");

                    b.Property<int>("Impressions")
                        .HasColumnType("integer")
                        .HasColumnName("impressions");

                    b.Property<int>("Orders")
                        .HasColumnType("integer")
                        .HasColumnName("orders");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("revenue");

                    b.Property<decimal>("Spend")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("spend");

                    b.HasKey("CampaignId", "Date");

                    b.ToTable("campaign_statistics", (string)null);
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.DemoFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnswersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("answers_json");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("GeneralComment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("general_comment");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("demo_feedbacks", (string)null);
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.Nomenclature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("name");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<string>("WbNomenclatureId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("wb_nomenclature_id");

                    b.HasKey("Id");

                    b.HasIndex("StoreId", "WbNomenclatureId")
                        .IsUnique();

                    b.ToTable("nomenclatures", (string)null);
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.Seller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("access_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DemoExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("demo_expires_at_utc");

                    b.Property<DateTime?>("DemoFeedbackSubmittedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("demo_feedback_submitted_at_utc");

                    b.Property<DateTime?>("DemoStartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("demo_started_at_utc");

                    b.Property<int>("DemoStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("demo_status");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsDemoUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_demo_user");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("MvpAccessGrantedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mvp_access_granted_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("sellers", (string)null);
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiKey")
                        .HasColumnType("text")
                        .HasColumnName("api_key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id");

                    b.Property<DateTime?>("JamCheckedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("jam_checked_at_utc");

                    b.Property<string>("JamStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("unknown")
                        .HasColumnName("jam_status");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_at");

                    b.Property<string>("Marketplace")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Wildberries")
                        .HasColumnName("marketplace");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<DateTime?>("TokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("token_expires_at_utc");

                    b.Property<string>("TokenLastFour")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("token_last_four");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.HasIndex("Marketplace", "ExternalId")
                        .IsUnique()
                        .HasFilter("external_id IS NOT NULL");

                    b.ToTable("stores", (string)null);
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.TelegramBotState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("NextUpdateId")
                        .HasColumnType("bigint")
                        .HasColumnName("next_update_id");

                    b.HasKey("Id");

                    b.ToTable("telegram_bot_state", (string)null);
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.TelegramChat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LinkedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at_utc");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.HasKey("Id");

                    b.HasIndex("ChatId")
                        .IsUnique();

                    b.HasIndex("SellerId");

                    b.ToTable("telegram_chats", (string)null);
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.TelegramDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid")
                        .HasColumnName("chat_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("error_code");

                    b.Property<DateOnly>("ReportDate")
                        .HasColumnType("date")
                        .HasColumnName("report_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("StoreId", "ChatId", "ReportDate")
                        .IsUnique();

                    b.ToTable("telegram_deliveries", (string)null);
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.TelegramLinkCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code_hash");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("CodeHash")
                        .IsUnique();

                    b.HasIndex("SellerId");

                    b.ToTable("telegram_link_codes", (string)null);
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.WbCampaignNorms", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<string>("CustomName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("custom_name");

                    b.Property<decimal?>("DeviationPercent")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("deviation_percent");

                    b.Property<string>("Goal")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("goal");

                    b.Property<int?>("MinClicks")
                        .HasColumnType("integer")
                        .HasColumnName("min_clicks");

                    b.Property<decimal?>("MinCtr")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("min_ctr");

                    b.Property<int?>("MinOrders")
                        .HasColumnType("integer")
                        .HasColumnName("min_orders");

                    b.Property<decimal?>("MinSpend")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("min_spend");

                    b.Property<decimal?>("TargetDrr")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("target_drr");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("CampaignId");

                    b.ToTable("wb_campaign_norms", (string)null);
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.WbClusterStatistic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AveragePosition")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("average_position");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<int?>("Carts")
                        .HasColumnType("integer")
                        .HasColumnName("carts");

                    b.Property<int?>("Clicks")
                        .HasColumnType("integer")
                        .HasColumnName("clicks");

                    b.Property<string>("ClusterName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cluster_name");

                    b.Property<decimal?>("Cpc")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("cpc");

                    b.Property<decimal?>("Cpm")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("cpm");

                    b.Property<decimal?>("Ctr")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("ctr");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("NomenclatureId")
                        .HasColumnType("uuid")
                        .HasColumnName("nomenclature_id");

                    b.Property<int?>("OrderedProducts")
                        .HasColumnType("integer")
                        .HasColumnName("ordered_products");

                    b.Property<int?>("Orders")
                        .HasColumnType("integer")
                        .HasColumnName("orders");

                    b.Property<decimal>("Spend")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("spend");

                    b.Property<int?>("Views")
                        .HasColumnType("integer")
                        .HasColumnName("views");

                    b.HasKey("Id");

                    b.HasIndex("NomenclatureId");

                    b.HasIndex("CampaignId", "NomenclatureId", "Date", "ClusterName")
                        .IsUnique();

                    b.ToTable("wb_cluster_statistics", (string)null);
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.WbJamSearchQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("AddToCart")
                        .HasColumnType("bigint")
                        .HasColumnName("add_to_cart");

                    b.Property<decimal?>("AveragePosition")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("average_position");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<long?>("Frequency")
                        .HasColumnType("bigint")
                        .HasColumnName("frequency");

                    b.Property<DateTime>("LoadedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_at_utc");

                    b.Property<decimal?>("MedianPosition")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("median_position");

                    b.Property<Guid>("NomenclatureId")
                        .HasColumnType("uuid")
                        .HasColumnName("nomenclature_id");

                    b.Property<long?>("OpenCard")
                        .HasColumnType("bigint")
                        .HasColumnName("open_card");

                    b.Property<long?>("Orders")
                        .HasColumnType("bigint")
                        .HasColumnName("orders");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("search_text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<long?>("WeekFrequency")
                        .HasColumnType("bigint")
                        .HasColumnName("week_frequency");

                    b.HasKey("Id");

                    b.HasIndex("NomenclatureId");

                    b.HasIndex("StoreId", "NomenclatureId", "StartDate", "EndDate", "SearchText")
                        .IsUnique();

                    b.ToTable("wb_jam_search_queries", (string)null);
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.WbNormRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("settings_json");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("StoreId", "CampaignId", "Version");

                    b.ToTable("wb_norm_revisions", (string)null);
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.WbRecommendationDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("RecommendationKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("recommendation_key");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("SellerId", "RecommendationKey", "StartDate", "EndDate")
                        .IsUnique();

                    b.ToTable("wb_recommendation_decisions", (string)null);
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.WbStoreNorms", b =>
                {
                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<decimal>("DeviationPercent")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("deviation_percent");

                    b.Property<int>("MinClicks")
                        .HasColumnType("integer")
                        .HasColumnName("min_clicks");

                    b.Property<decimal>("MinCtr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8,2)")
                        .HasDefaultValue(3m)
                        .HasColumnName("min_ctr");

                    b.Property<int>("MinOrders")
                        .HasColumnType("integer")
                        .HasColumnName("min_orders");

                    b.Property<decimal>("MinSpend")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("min_spend");

                    b.Property<decimal>("TargetDrr")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("target_drr");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("StoreId");

                    b.ToTable("wb_store_norms", (string)null);
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.WbSyncJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("CampaignIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("campaign_ids_json");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("error_code");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("fullstats")
                        .HasColumnName("kind");

                    b.Property<DateTime?>("LastRequestAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_request_at_utc");

                    b.Property<DateTime>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<int>("NextCampaignOffset")
                        .HasColumnType("integer")
                        .HasColumnName("next_campaign_offset");

                    b.Property<string>("PairIdsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("pair_ids_json");

                    b.Property<Guid?>("RetriedFromJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("retried_from_job_id");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasDefaultValue("queued")
                        .HasColumnName("stage");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("WaitReason")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("wait_reason");

                    b.HasKey("Id");

                    b.HasIndex("StoreId")
                        .IsUnique()
                        .HasFilter("status IN ('pending', 'running')");

                    b.HasIndex("StoreId", "Status", "NextAttemptAtUtc");

                    b.ToTable("wb_sync_jobs", (string)null);
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.WbSyncJobEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("error_code");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<int>("ProcessedCount")
                        .HasColumnType("integer")
                        .HasColumnName("processed_count");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("stage");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "OccurredAtUtc");

                    b.ToTable("wb_sync_job_events", (string)null);
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.Campaign", b =>
                {
                    b.HasOne("Ecomads.WebApplication.Data.Models.Store", "Store")
                        .WithMany("Campaigns")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_campaigns_stores_store_id");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.CampaignNomenclatureStatistics", b =>
                {
                    b.HasOne("Ecomads.WebApplication.Data.Models.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecomads.WebApplication.Data.Models.Nomenclature", "Nomenclature")
                        .WithMany()
                        .HasForeignKey("NomenclatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Nomenclature");
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.CampaignStatistics", b =>
                {
                    b.HasOne("Ecomads.WebApplication.Data.Models.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.DemoFeedback", b =>
                {
                    b.HasOne("Ecomads.WebApplication.Data.Models.Seller", null)
                        .WithOne()
                        .HasForeignKey("Ecomads.WebApplication.Data.Models.DemoFeedback", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_demo_feedbacks_sellers_user_id");
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.Nomenclature", b =>
                {
                    b.HasOne("Ecomads.WebApplication.Data.Models.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_nomenclatures_stores_store_id");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.Store", b =>
                {
                    b.HasOne("Ecomads.WebApplication.Data.Models.Seller", "Seller")
                        .WithMany("Stores")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_stores_sellers_seller_id");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.TelegramChat", b =>
                {
                    b.HasOne("Ecomads.WebApplication.Data.Models.Seller", null)
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.TelegramDelivery", b =>
                {
                    b.HasOne("Ecomads.WebApplication.Data.Models.TelegramChat", null)
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecomads.WebApplication.Data.Models.Store", null)
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.TelegramLinkCode", b =>
                {
                    b.HasOne("Ecomads.WebApplication.Data.Models.Seller", null)
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.WbCampaignNorms", b =>
                {
                    b.HasOne("Ecomads.WebApplication.Data.Models.Campaign", null)
                        .WithOne()
                        .HasForeignKey("Ecomads.WebApplication.Data.Models.WbCampaignNorms", "CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.WbClusterStatistic", b =>
                {
                    b.HasOne("Ecomads.WebApplication.Data.Models.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecomads.WebApplication.Data.Models.Nomenclature", null)
                        .WithMany()
                        .HasForeignKey("NomenclatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.WbJamSearchQuery", b =>
                {
                    b.HasOne("Ecomads.WebApplication.Data.Models.Nomenclature", null)
                        .WithMany()
                        .HasForeignKey("NomenclatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecomads.WebApplication.Data.Models.Store", null)
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.WbNormRevision", b =>
                {
                    b.HasOne("Ecomads.WebApplication.Data.Models.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Ecomads.WebApplication.Data.Models.Store", null)
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.WbRecommendationDecision", b =>
                {
                    b.HasOne("Ecomads.WebApplication.Data.Models.Seller", null)
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.WbStoreNorms", b =>
                {
                    b.HasOne("Ecomads.WebApplication.Data.Models.Store", null)
                        .WithOne()
                        .HasForeignKey("Ecomads.WebApplication.Data.Models.WbStoreNorms", "StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.WbSyncJob", b =>
                {
                    b.HasOne("Ecomads.WebApplication.Data.Models.Store", null)
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.WbSyncJobEvent", b =>
                {
                    b.HasOne("Ecomads.WebApplication.Data.Models.WbSyncJob", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.Seller", b =>
                {
                    b.Navigation("Stores");
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.Store", b =>
                {
                    b.Navigation("Campaigns");
                });
#pragma warning restore 612, 618
        }
    }
}
