// <auto-generated />
using System;
using Ecomads.WebApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ecomads.WebApplication.Migrations
{
    [DbContext(typeof(EcomadsDbContext))]
    partial class EcomadsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.Compaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Budget")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("budget");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("number");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("compaigns", (string)null);
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.CompaignStatistics", b =>
                {
                    b.Property<Guid>("CompaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("compaign_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<float>("Clicks")
                        .HasColumnType("real")
                        .HasColumnName("clicks");

                    b.Property<float>("Ctr")
                        .HasColumnType("real")
                        .HasColumnName("ctr");

                    b.Property<float>("Drr")
                        .HasColumnType("real")
                        .HasColumnName("drr");

                    b.Property<float>("Revenue")
                        .HasColumnType("real")
                        .HasColumnName("revenue");

                    b.Property<float>("Spend")
                        .HasColumnType("real")
                        .HasColumnName("spend");

                    b.HasKey("CompaignId", "StartDate", "EndDate", "Type");

                    b.ToTable("compaign_statistics", (string)null);
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.DemoFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContinueTestingAnswer")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("continue_testing_answer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DashboardClarityScore")
                        .HasColumnType("integer")
                        .HasColumnName("dashboard_clarity_score");

                    b.Property<string>("GeneralComment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("general_comment");

                    b.Property<string>("MissingForRegularUsage")
                        .HasColumnType("text")
                        .HasColumnName("missing_for_regular_usage");

                    b.Property<string>("MostUsefulFeature")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("most_useful_feature");

                    b.Property<int>("RecommendationsUsefulnessScore")
                        .HasColumnType("integer")
                        .HasColumnName("recommendations_usefulness_score");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("WillingToPayAnswer")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("willing_to_pay_answer");

                    b.Property<string>("WrongOrQuestionableRecommendations")
                        .HasColumnType("text")
                        .HasColumnName("wrong_or_questionable_recommendations");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("demo_feedbacks", (string)null);
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.KeywordStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("AvgPosition")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_position");

                    b.Property<int?>("Clicks")
                        .HasColumnType("integer")
                        .HasColumnName("clicks");

                    b.Property<Guid>("CompaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("compaign_id");

                    b.Property<decimal?>("Cpm")
                        .HasColumnType("numeric")
                        .HasColumnName("cpm");

                    b.Property<double?>("Ctr")
                        .HasColumnType("double precision")
                        .HasColumnName("ctr");

                    b.Property<double?>("Drr")
                        .HasColumnType("double precision")
                        .HasColumnName("drr");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<int?>("Frequency")
                        .HasColumnType("integer")
                        .HasColumnName("frequency");

                    b.Property<int?>("Impressions")
                        .HasColumnType("integer")
                        .HasColumnName("impressions");

                    b.Property<int?>("Orders")
                        .HasColumnType("integer")
                        .HasColumnName("orders");

                    b.Property<string>("Phrase")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("phrase");

                    b.Property<decimal?>("Revenue")
                        .HasColumnType("numeric")
                        .HasColumnName("revenue");

                    b.Property<decimal?>("Spend")
                        .HasColumnType("numeric")
                        .HasColumnName("spend");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("CompaignId");

                    b.ToTable("keyword_statistics", (string)null);
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.LlmUsageEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("BothubCaps")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("bothub_caps");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("integer")
                        .HasColumnName("completion_tokens");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_message");

                    b.Property<decimal?>("EstimatedCostRub")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("estimated_cost_rub");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("http_status_code");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("is_success");

                    b.Property<Guid?>("KeywordId")
                        .HasColumnType("uuid")
                        .HasColumnName("keyword_id");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("model");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("operation_name");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_tokens");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("provider");

                    b.Property<string>("RequestMetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("request_metadata_json");

                    b.Property<string>("ResponseMetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_metadata_json");

                    b.Property<int?>("TotalTokens")
                        .HasColumnType("integer")
                        .HasColumnName("total_tokens");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("IsSuccess");

                    b.HasIndex("Model");

                    b.HasIndex("OperationName");

                    b.HasIndex("Provider");

                    b.HasIndex("UserId");

                    b.ToTable("llm_usage_events", (string)null);
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.ProductUsageEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("event_name");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("feature_name");

                    b.Property<string>("IpHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ip_hash");

                    b.Property<Guid?>("KeywordId")
                        .HasColumnType("uuid")
                        .HasColumnName("keyword_id");

                    b.Property<Guid?>("LlmUsageId")
                        .HasColumnType("uuid")
                        .HasColumnName("llm_usage_id");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Method")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("method");

                    b.Property<string>("Path")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("path");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("EventName");

                    b.HasIndex("FeatureName");

                    b.HasIndex("LlmUsageId");

                    b.HasIndex("UserId");

                    b.ToTable("product_usage_events", (string)null);
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.Recommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdditionalData")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("additional_data");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExpectedEffect")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("expected_effect");

                    b.Property<string>("FullResponse")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_response");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("goal");

                    b.Property<string>("Problem")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("problem");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt");

                    b.Property<string>("RecommendationText")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("recommendation_text");

                    b.Property<string>("RequestMetadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("request_metadata");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("новая")
                        .HasColumnName("status");

                    b.Property<DateTime?>("StatusUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_updated_at");

                    b.Property<string>("UserComment")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("user_comment");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("recommendations", (string)null);
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.RecommendationInsightEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("id");

                    b.Property<decimal?>("ActualEffectMoney")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("actual_effect_money");

                    b.Property<string>("ActualEffectStatus")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("actual_effect_status");

                    b.Property<string>("AllowedActionsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("allowed_actions");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<string>("ConfidenceLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("confidence_level");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DecisionStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("decision_status");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("entity_name");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<decimal?>("ExpectedEffectMoney")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("expected_effect_money");

                    b.Property<string>("ExpectedEffectText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expected_effect_text");

                    b.Property<string>("ExpectedEffectType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("expected_effect_type");

                    b.Property<string>("ForbiddenActionsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("forbidden_actions");

                    b.Property<string>("InsightType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("insight_type");

                    b.Property<string>("MetricsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("metrics");

                    b.Property<DateTime>("PeriodFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_from");

                    b.Property<DateTime>("PeriodTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_to");

                    b.Property<string>("PriorityLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("priority_level");

                    b.Property<double>("PriorityScore")
                        .HasColumnType("double precision")
                        .HasColumnName("priority_score");

                    b.Property<string>("ReasonCodesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("reason_codes");

                    b.Property<Guid>("RecommendationRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("recommendation_run_id");

                    b.Property<string>("RecommendedAction")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("recommended_action");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserComment")
                        .HasColumnType("text")
                        .HasColumnName("user_comment");

                    b.HasKey("Id");

                    b.HasIndex("DecisionStatus");

                    b.HasIndex("RecommendationRunId");

                    b.HasIndex("CampaignId", "EntityType", "EntityId");

                    b.ToTable("recommendation_insights", (string)null);
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.Seller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("access_type")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DemoExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("demo_expires_at_utc");

                    b.Property<DateTime?>("DemoFeedbackSubmittedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("demo_feedback_submitted_at_utc");

                    b.Property<DateTime?>("DemoStartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("demo_started_at_utc");

                    b.Property<int>("DemoStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("demo_status")
                        .HasDefaultValue(0);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsDemoUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("is_demo_user")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("MvpAccessGrantedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mvp_access_granted_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("sellers", (string)null);
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("api_key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_at");

                    b.Property<string>("Marketplace")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Wildberries")
                        .HasColumnName("marketplace");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.ToTable("stores", (string)null);
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.Compaign", b =>
                {
                    b.HasOne("Ecomads.WebApplication.Data.Models.Store", "Store")
                        .WithMany("Compaigns")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_compaigns_stores_store_id");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.CompaignStatistics", b =>
                {
                    b.HasOne("Ecomads.WebApplication.Data.Models.Compaign", null)
                        .WithMany()
                        .HasForeignKey("CompaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.DemoFeedback", b =>
                {
                    b.HasOne("Ecomads.WebApplication.Data.Models.Seller", null)
                        .WithOne()
                        .HasForeignKey("Ecomads.WebApplication.Data.Models.DemoFeedback", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_demo_feedbacks_sellers_user_id");
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.KeywordStatistics", b =>
                {
                    b.HasOne("Ecomads.WebApplication.Data.Models.Compaign", "Compaign")
                        .WithMany()
                        .HasForeignKey("CompaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_keyword_statistics_compaigns_compaign_id");

                    b.Navigation("Compaign");
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.ProductUsageEvent", b =>
                {
                    b.HasOne("Ecomads.WebApplication.Data.Models.LlmUsageEvent", null)
                        .WithMany()
                        .HasForeignKey("LlmUsageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_product_usage_events_llm_usage_events_llm_usage_id");
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.Recommendation", b =>
                {
                    b.HasOne("Ecomads.WebApplication.Data.Models.Compaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_recommendations_compaigns_campaign_id");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.RecommendationInsightEntity", b =>
                {
                    b.HasOne("Ecomads.WebApplication.Data.Models.Compaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_recommendation_insights_compaigns_campaign_id");

                    b.HasOne("Ecomads.WebApplication.Data.Models.Recommendation", "RecommendationRun")
                        .WithMany()
                        .HasForeignKey("RecommendationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_recommendation_insights_recommendations_recommendation_run_id");

                    b.Navigation("RecommendationRun");
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.Store", b =>
                {
                    b.HasOne("Ecomads.WebApplication.Data.Models.Seller", "Seller")
                        .WithMany("Stores")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_stores_sellers_seller_id");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.Seller", b =>
                {
                    b.Navigation("Stores");
                });

            modelBuilder.Entity("Ecomads.WebApplication.Data.Models.Store", b =>
                {
                    b.Navigation("Compaigns");
                });
#pragma warning restore 612, 618
        }
    }
}
